language: java
jdk:
- openjdk8
script: mvn clean package
notifications:
  slack:
    secure: K8bFISZIZ29n/O+bMz/+CZTHuwtyzU62qToGYZcemh7KN6jlBLXdFBrKqkS78XckQQSiwEatRyQTDRGgHCXHrAU526PkVPcu6PuVQcUinYMvxXkEQ5yTJauiEMpIDA2vBLIOKojDK9t0dBuOAgtbhXsVUYAJVcEXsJCZGsx7elru2xmlLhEU0PS/N/WG5098RCfGrJ7k9unKk9GVZFibwzEysf5w0auDr5ewh6jHJiXBg+rEnp/1oTA546MO7Q7SAQPC+EmI/NhbCWASpFHNgvSTegTamFIExEjPR+L5n5eBbyuNoZ5HubbsLb1V0IGdyi7nX3OGmDqKWZ8Cb96uMiLLFGMo5C3VkvkGPGzra10jLuarfIB3kuWe7D8Bm6KewQLJ6hL41m9VWkWVUHI9Q3yqPSo7sFLCAloJie6R+HhFjxu4FfgSmdWMbeIUS95zeiwdaTcATTQz8hqZ+LaYAAU/cEpj5efsIMBrpkc8J3dVTMbDiItz2CMKvXFWSSoN5Klx66488mYMiZnQ+ufTSHWCskDr04Zllh/50JDosBkL4fOelrPgBYz68aLoVnMYAKC1m+kSejYNE8VyNbQwbixecr2+EufLgw88d+080izTjodjXJDt68UT9+8Fv62zrsvBWjUqqRgvJvT7NHi3u/1ooqVY8z7CNrZxYEKV20s=
